version: "3.7"

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
      args:
        - HOST=localhost
    depends_on:
      - app
    ports:
      - "80:80"
      - "5432:5432"

  app:
    depends_on:
      - db
      - opensearch
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  opensearch:
    image: "opensearchproject/opensearch:latest"
    depends_on:
      - db
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node

  db:
    image: postgres:15.2
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
